import { chromium } from "playwright";
const B = "http://localhost:3000";
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1400, height: 900 }, deviceScaleFactor: 2 });
const p = await c.newPage();
const errs = [];
p.on("pageerror", (e) => errs.push("PAGEERROR " + e.message));
p.on("console", (m) => m.type() === "error" && errs.push("CONSOLE " + m.text()));
await p.goto(`${B}/en/login`, { waitUntil: "networkidle" });
await p.screenshot({ path: ".impeccable/review/desk-login.png" });
await p.fill("#email", "admin@example.com");
await p.fill("#password", "throughline");
await p.getByRole("button", { name: "Sign in" }).click();
await p.waitForURL("**/workspace", { timeout: 10000 });
await p.waitForTimeout(2500);
await p.screenshot({ path: ".impeccable/review/desk-home.png" });
await p.locator("aside button", { hasText: "Topics" }).first().click();
await p.waitForTimeout(1800);
await p.screenshot({ path: ".impeccable/review/desk-topics.png" });
console.log(errs.length ? errs.slice(0, 5).join("\n") : "no errors");
await b.close();
