import { chromium } from "playwright";
const B = "http://localhost:3000";
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const p = await c.newPage();
await p.goto(`${B}/en/login`, { waitUntil: "networkidle" });
await p.fill("#email", "admin@example.com"); await p.fill("#password", "throughline");
await p.getByRole("button", { name: "Sign in" }).click();
await p.waitForURL("**/workspace", { timeout: 8000 });
await p.waitForTimeout(2500);
await p.screenshot({ path: ".impeccable/review/first-1-landing.png" });
const nav = (n) => p.locator("nav[aria-label] button", { hasText: n }).first();
await nav("Content task").click(); await p.waitForTimeout(1500);
await p.screenshot({ path: ".impeccable/review/first-2-task.png" });
await b.close();
console.log("ok");
