/*
  Regenerates lib/frappe-tokens.css from the frappe-ui package.
  Run after bumping frappe-ui:  node scripts/frappe-tokens.mjs
*/
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

const dir = mkdtempSync(join(tmpdir(), "fui-"));
const tgz = execSync("npm pack frappe-ui --silent", { cwd: dir }).toString().trim().split("\n").pop();
execSync(`tar xzf ${tgz}`, { cwd: dir });
const raw = JSON.parse(readFileSync(join(dir, "package/tailwind/colors.json"), "utf8"));

const flat = {};
(function walk(o, path = "") {
  for (const [k, v] of Object.entries(o)) {
    const p = path ? `${path}/${k}` : k;
    if (v && typeof v === "object") walk(v, p);
    else flat[p] = v;
  }
})(raw);

const out = { light: {}, dark: {} };
for (const [k, v] of Object.entries(flat)) {
  const m = /^themedVariables\/(light|dark)\/(.+)$/.exec(k);
  if (!m) continue;
  const hex = flat[String(v).trim()];
  if (hex) out[m[1]][m[2].replaceAll("/", "-")] = hex;
}

let css = "/*\n  Frappe UI colour tokens, resolved from the frappe-ui npm package.\n  Generated by scripts/frappe-tokens.mjs. Do not hand-edit.\n*/\n";
for (const [mode, sel] of [["light", '[data-surface="app"]'], ["dark", '[data-theme="dark"] [data-surface="app"]']]) {
  css += `\n${sel} {\n`;
  for (const name of Object.keys(out[mode]).sort()) css += `  --${name}: ${out[mode][name]};\n`;
  css += "}\n";
}
writeFileSync("lib/frappe-tokens.css", css);
console.log(`frappe tokens: ${Object.keys(out.light).length} light, ${Object.keys(out.dark).length} dark`);
