import { chromium } from "playwright";
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1400, height: 900 }, deviceScaleFactor: 2 });
const p = await c.newPage();
const errs = [];
p.on("pageerror", (e) => errs.push("PAGEERROR " + e.message));
await p.goto("http://localhost:3000/en/login", { waitUntil: "networkidle" });
await p.fill("#email", "admin@example.com"); await p.fill("#password", "throughline");
await p.getByRole("button", { name: "Sign in" }).click();
await p.waitForURL("**/workspace", { timeout: 10000 });
await p.waitForTimeout(2000);
await p.locator("aside button", { hasText: "Topics" }).first().click();
await p.waitForTimeout(2000);
await p.screenshot({ path: ".impeccable/review/list-topics.png" });
console.log(errs.length ? errs.join("\n") : "no errors");
await b.close();
